### ISSUE TITLE
Problem with dataset with 120k images

### ISSUE THREAD

**Issue by whoisraibolt** [qizhen816/Tensorflow-with-own-data#7]
The code works fine, however I'm trying to create a dataset with approximately 120k images.

But I'm getting the following error:

Any idea how to fix this?

```
Traceback (most recent call last):
  File "makedata.py", line 25, in <module>
    p1 = pickle.dumps(d, 2)
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 492, in save_string
    self.write(BINSTRING + pack("<i", n) + obj)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by whoisraibolt** [comment]
I fixed this!

I've used joblib, which is more efficient on large data than pickle.

```
# Import
from sklearn.externals import joblib

# os.path.join([local], [filename])
filename = os.path.join('/home', 'test.pkl')

# Generate the pkl file, save as .gz
# Dumping in a gzip compressed file using a compress level of 3
file = joblib.dump(d, filename + '.gz', compress=('gzip', 3))
```
